---
- name: Create the Nomad manifest
  template:
    src: cabify.nomad.j2
    dest: "{{ nomad_jobs_dir }}/cabify.nomad"
    mode: 0644
  register: cabify_manifest

- name: Deploy Cabify
  command: nomad run {{ nomad_jobs_dir }}/cabify.nomad
  when: cabify_manifest.changed or cabify_dockerfile.changed
