---
- name: Create the Nomad manifest
  template:
    src: cabify.nomad.j2
    dest: "{{ nomad_jobs_dir }}/cabify.nomad"
    mode: 0644
  notify: deploy cabify application
  register: cabify_manifest_changed

- name: Deploy Cabify
  command: nomad run {{ nomad_jobs_dir }}/cabify.nomad
  when: cabify_manifest_changed|success
