---
- name: Configure the Docker registry
  template:
    src: docker-registry.nomad.j2
    dest: "{{ nomad_jobs_dir }}/docker-registry.nomad"
    owner: root
    group: root
    mode: 0644
  register: docker_registry_manifest

- block:
  - name: Deploy the Docker registry
    command: nomad run {{ nomad_jobs_dir }}/docker-registry.nomad

  - name: Wait the Docker registry to become available
    wait_for:
      host: localhost
      port: 5000
      timeout: 30
      
  when: docker_registry_manifest.changed
  